# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [FFA, FOX]
patreon: # Replace with a single Patreon username liberty mutual
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username Viceland
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username ontv4u
otechie: # Replace with a single Otechie username beachbody
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://pornhub.com','https://sbabes.com','Https://marchofdimes.orh','Https://Adamandeve.com','Https://youporn.com','https://hunterz.io']
